# Plugin messages
messages:
  level_up_local_gen_success: "&a&l%s &b&lhas upgraded the local generator to tier &e&l%s"
  level_up_shared_gen_success: "&a&l%s &b&lhas upgraded the %s generator to tier &e&l%s"
  level_up_local_gen_failed: "&cReached tier limit."
  level_up_shared_gen_failed: "&cReached tier limit."
  too_far_from_base: "&eYou're too far from your base."

# List of worlds related to BedWars
worlds:
  - lighthouse

products:
  category_filter:
    - bedwar_items
    - bedwar_upgrades
  auto_dye_items:
    wool:
      '1':
        material: "%s_wool"
        amount: 16
  extra_executions:
    upLocalGen:
      - generator::upgrade_local
    upDiamondGen:
      - generator::upgrade_shared { Diamond Gen }
    upEmeraldGen:
      - generator::upgrade_shared { Emerald Gen }
    healthPool:
      - pool::remove_potion { * }
      - pool::set_potion { 0; regeneration; 0; 20; teammates }
    slownessPool:
      - pool::remove_potion { * }
      - pool::set_potion { 0; slow_digging; 0; 20; enemies }
      - pool::set_potion { 1; slow; 0; 20; enemies }

arenas:
  bw_demo:
    openable_category_distance: 7
    shopkeepers:
      '1':
        entity_type: villager
        category: bedwar_items
        locations:
          - lighthouse 23.32 65.00 -88.05 270.60 -0.45
          - lighthouse -27.70 65.00 -87.92 268.50 3.00
          - lighthouse -85.16 65.00 -19.30 181.50 2.25
          - lighthouse -85.09 65.00 31.70 181.80 2.10
          - lighthouse -16.35 65.00 88.95 90.90 0.90
          - lighthouse 34.63 65.00 89.08 91.95 1.65
          - lighthouse 92.12 65.00 20.30 1.50 2.40
          - lighthouse 92.05 65.00 -30.70 359.10 0.15
      '2':
        entity_type: blaze
        category: bedwar_upgrades
        locations:
          - lighthouse 34.69 65.00 -87.90 90.15 5.40
          - lighthouse -16.31 65.00 -87.96 90.30 3.00
          - lighthouse -84.94 65.00 -30.70 0.30 1.95
          - lighthouse -85.01 65.00 20.44 1.65 3.60
          - lighthouse -27.70 65.00 89.16 269.40 2.10
          - lighthouse 23.40 65.00 88.84 272.40 2.55
          - lighthouse 91.91 65.00 31.70 179.40 1.20
          - lighthouse 92.07 65.00 -19.30 179.85 1.50
    local_generator:
      locations:
        - lighthouse 29.42 66.5 -91.58 0 0
        - lighthouse -22.58 66.5 -91.56 0 0
        - lighthouse -88.69 66.5 -25.50 0 0
        - lighthouse -88.70 66.5 26.54 0 0
        - lighthouse -22.40 66.5 92.70 0 0
        - lighthouse 29.46 66.5 92.70 0 0
        - lighthouse 95.70 66.5 26.60 0 0
        - lighthouse 95.69 66.5 -25.49 0 0
      tiers:
        '1':
          produce_delay: 60
          items:
            '1':
              material: iron_ingot
              amount:
                max: 2
              chance: 10
            '2':
              material: gold_ingot
              chance: 4
        '2':
          produce_delay: 60
          items:
            '1':
              material: iron_ingot
              amount:
                max: 3
              chance: 10
            '2':
              material: gold_ingot
              amount:
                max: 2
              chance: 4
        '3':
          produce_delay: 40
          items:
            '1':
              material: iron_ingot
              amount:
                min: 2
                max: 4
              chance: 10
            '2':
              material: gold_ingot
              amount:
                max: 3
              chance: 5
    shared_generators:
      '1':
        name: "Diamond Gen"
        locations:
          - lighthouse 55.63 67.5 -51.37 0 0
          - lighthouse -48.60 67.5 -51.68 0 0
          - lighthouse -48.37 67.5 52.33 0 0
          - lighthouse 55.63 67.5 52.49 0 0
        hologram:
          enabled: true
          offset: 0.35
          lines:
          - "&b&lDiamond Generator"
          - "&e&lTier {__tier__}"
          - "&c&l{__time_left__}"
        tiers:
          '1':
            produce_delay: 600
            items:
              '1':
                material: diamond
          '2':
            produce_delay: 560
            items:
              '1':
                material: diamond
          '3':
            produce_delay: 500
            items:
              '1':
                material: diamond
      '2':
        name: "Emerald Gen"
        locations:
          - lighthouse -6.56 66.25 14.47 0 0
          - lighthouse 13.52 66.25 -13.48 0 0
          - lighthouse 3.54 87.5 -6.38 0 0
          - lighthouse 3.59 87.5 7.36 0 0
        hologram:
          enabled: true
          offset: 0.35
          lines:
            - "&a&lEmerald Generator"
            - "&e&lTier {__tier__}"
            - "&c&l{__time_left__}"
        tiers:
          '1':
            produce_delay: 1000
            items:
              '1':
                material: emerald
          '2':
            produce_delay: 900
            items:
              '1':
                material: emerald
          '3':
            produce_delay: 760
            items:
              '1':
                material: emerald
